name: amap_location_fluttify
description: A new flutter plugin project.
version: 0.0.0
author: yohom <382146139@qq.com>
homepage: https://github.com/fluttify-community/amap_location_fluttify

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: me.yohom.amap_location_fluttify
    pluginClass: AmapLocationFluttifyPlugin
