name: amap_location_fluttify
description: An `Amap` Location Component, Powered by `Fluttify` Engine.
version: 0.5.1+a918944
author: yohom <382146139@qq.com>
homepage: https://github.com/fluttify-project/amap_location_fluttify

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  foundation_fluttify: ^0.2.7
  amap_core_fluttify: ^0.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: me.yohom.amap_location_fluttify
    pluginClass: AmapLocationFluttifyPlugin