name: amap_location_fluttify
description: An `Amap` location component, based on `fluttify` engine.
version: 0.3.0+8cf796c
author: yohom <382146139@qq.com>
homepage: https://github.com/fluttify-project/amap_location_fluttify

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  foundation_fluttify: ^0.1.0
  amap_core_fluttify: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: me.yohom.amap_location_fluttify
    pluginClass: AmapLocationFluttifyPlugin
