name: amap_location_fluttify
description: An `Amap` Location Component, Powered By `Fluttify` Engine.
version: 0.8.0+ea37ae9
author: yohom <382146139@qq.com>
homepage: https://github.com/fluttify-project/amap_location_fluttify

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.13 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  amap_core_fluttify: 
    git:
      url: https://github.com/AngusPei/amap_core_fluttify.git
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: me.yohom.amap_location_fluttify
        pluginClass: AmapLocationFluttifyPlugin
      ios:
        pluginClass: AmapLocationFluttifyPlugin
